# Generated by Django 3.1.6 on 2021-02-28 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('comment_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('thread', models.IntegerField()),
                ('comment_level', models.IntegerField()),
                ('comment', models.CharField(max_length=5000)),
                ('argumentation', models.IntegerField()),
                ('constructivity', models.IntegerField()),
                ('positive_stance', models.IntegerField()),
                ('negative_stance', models.IntegerField()),
                ('target_person', models.IntegerField()),
                ('target_group', models.IntegerField()),
                ('stereotype', models.IntegerField()),
                ('sarcasm', models.IntegerField()),
                ('mockery', models.IntegerField()),
                ('insult', models.IntegerField()),
                ('improper_language', models.IntegerField()),
                ('aggressiveness', models.IntegerField()),
                ('intolerance', models.IntegerField()),
                ('toxicity', models.IntegerField()),
                ('toxicity_level', models.IntegerField()),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataVisualization.document')),
            ],
        ),
    ]
