# Generated by Django 3.1.6 on 2021-02-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVisualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='aggressiveness',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='argumentation',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='comment_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='comment_level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='constructivity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='improper_language',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='insult',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='intolerance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='mockery',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='negative_stance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='positive_stance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='sarcasm',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='stereotype',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='target_group',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='target_person',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='thread',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='toxicity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='toxicity_level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
